title: Emmily Cotzojay Portfolio
description: My personal portfolio website
baseurl: "/emmilys-portfolio"  # your repo name, change if needed
url: "https://ecotzojay.github.io"  # your GitHub Pages URL (without trailing slash)
theme: minima
plugins:
  - jekyll-feed  # optional, for RSS feed support